FROM raspbian/stretch

RUN echo "deb http://mirrors.tuna.tsinghua.edu.cn/raspbian/raspbian stretch main contrib non-free rpi firmware" > /etc/apt/sources.list; \
    echo "deb-src http://mirrors.tuna.tsinghua.edu.cn/raspbian/raspbian stretch main contrib non-free rpi firmware" >> /etc/apt/sources.list; \
    echo "deb http://mirror.tuna.tsinghua.edu.cn/raspberrypi/ stretch main ui" > /etc/apt/sources.list.d/raspi.list; \
    echo "deb-src http://mirror.tuna.tsinghua.edu.cn/raspberrypi/ stretch main ui" >> /etc/apt/sources.list.d/raspi.list;

RUN apt-get update && apt-get -y install python3 python3-pip

RUN pip3 install bottle requests gevent

WORKDIR /home/pi/fileUploader

COPY ./server/getPos.py ./getPos.py

ENV PYTHONUNBUFFERED=0

ENTRYPOINT [ "python3", "getPos.py" ]

EXPOSE 8080